version: '3'
services:
  db:
    image: "postgres:10.4"
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: "hibernate"
        POSTGRES_PASSWORD: "teste123"
        POSTGRES_DB: "hibernate"
